/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import spock.lang.Unroll

class StringCalculatorTest extends Specification {

    def sc = new StringCalculator()

  @Unroll
  def "Testing an empty string should return cero"() {
      
    when:
      def result = sc.add("")
    then:
      result == 0
  }

  @Unroll
  def "Testing one number, should return the same number"() {
    
    given:"a string"
      String string = strings
    when:"pass the string to method add"
      Integer result = sc.add(string)
    then:
      result == sameNumber
    where:
      strings ||  sameNumber
      "1"     ||  1
      "3"     ||  3 
      "7"     ||  7
  }

  @Unroll
  def "Testing two numbers, should return the sum of numbers"() {
    
    given:"a string"
      String string = strings
    when:
      def result = sc.add(string)
    then:
      result == sumNumbers
    where:
      strings    ||  sumNumbers
      "1,2"      ||  3
      "3,4"      ||  7 
      "7,8"      ||  15
  }

  @Unroll
  def "Testing any numbers, should return the sum of numbers"() {
    
    given:"a string"
      String string = strings
    when:
      def result = sc.add(string)
    then:
      result == sumNumbers
    where:
      strings                       ||  sumNumbers
      "1,2,3"                       ||  6
      "3,4,5,6,7,8"                 ||  33 
      "1,1,1,1,1,1,1,1,1,1,1,1,1,1" ||  14
  }

  @Unroll
  def "Testing any numbers with new lines between them, should return the sum of numbers"() {
    
    given:"a string"
      String string = strings
    when:
      def result = sc.add(string)
    then:
      result == sumNumbers
    where:
      strings                             ||  sumNumbers
      "1,2\n3"                            ||  6
      "3\n4,5\n6,7\n8"                    ||  33 
      "1\n1\n1\n1\n1,1,1,1,1,1\n1,1\n1,1" ||  14
  }

  @Unroll
  def "Testing any numbers with new lines between them, should return the sum of numbers"() {
    
    given:"a string"
      String string = strings
    when:
        def result = sc.add(string)
    then:
        result == sumNumbers
    where:
        strings                             ||  sumNumbers
        "//;\n1;2;3"                        ||  6
        "//#\n3#4#5#6#7#8"                  ||  33 
        "//|\n1|1|1|1|1|1|1|1|1|1|1|1|1|1"  ||  14
  }

  @Unroll
  def "Testing negative numbers in the string, should throw exception"() {
    
    given:"a string"
      String string = strings
    when:
      def result = sc.add(string)
    then:
      def e = thrown(RuntimeException)
      e.message == errorMessage
    where:
      strings                 ||  errorMessage
      "1,2,3,-4,5,6"          ||  "negatives not allowed -4"
      "1,-2,3,-4,5,-6"        ||  "negatives not allowed -2 -4 -6"
          
  }

}
